### PR TITLE
fixed ssn and NaN values

### LINKED ISSUE #25: missing numeric values are set to "NaN"
I've seen this for Loan Down Payment and Loan LTV, as below. There may be others; all numeric fields should be checked. 

screen shot 2015-06-18 at 4 35 59 pm

### PR DESCRIPTION
**Pull request by jgrayson676**
fix #25

### CODE REVIEW

File: spec/inbound_spec.coffee [hunk 1]
```diff
@@ -86,6 +86,9 @@ describe 'Inbound', ->
       it 'should parse first mortgage balance', ->
         assert.equal '75000', shortform.request(req(xml())).mortgage.first_mortgage_balance
 
+      it 'should parse SSN', ->
+        assert.equal '123-45-6789', shortform.request(req(xml())).ssn
+
```
Comment (cgrayson) [inline spec/inbound_spec.coffee]: The "expected" value is supposed to be the 2nd parameter. 

And you may notice it isn't that way for a whole bunch of existing tests. Would you mind fixing those, too? (Make all those changes in a separate commit, so the "real" changes here can be differentiated.)
